id: PCDD7E965
initial_creation_type: input
source_metadata:
  title: Middle Way Series
  language: pt
  description: 'The following texts are available as part of our series on the Middle
    Way (Madhyamaka/Mādhyamika; dbu ma) philosophy:'
  volume:
    f69c56d3eab941aa9595c9f6a0f45ff0:
      title: Conveying the Essence of the Middle Way of Consequence
      parent: General
    b2e0bf32bca847d68c0dcd9648af701b:
      title: 'The Words of Candra: The Definitive Secret of the Great Middle Way of
        Consequence Beyond Extremes, the Fundamental Intent of All the Tathāgatas'
      parent: General
    50ec551980e44c518fd644878f38ea54:
      title: 'The Seed of Reasoning: Notes on the Five Great Logical Arguments of
        the Middle Way'
      parent: General
    db9dbd2c8c324fdbbc89f1f7c1311c4d:
      title: A Step-by-Step Meditation on the Definitive Meaning of the Great Middle
        Way
      parent: General
    1ab0d4c87c604248b2f2bf2e03ba1dfa:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: General
    342aad3da5f049ec9f9ed8eb2b0327f3:
      title: Profound Instruction on the View of the Middle Way
      parent: General
    0b05c6db41a549b4b3e7f5a3fd2f7178:
      title: 'Clarifying the Essence: A Summary of the Instructions on the View of
        the Middle Way'
      parent: General
    ef41d17536804fbc95856a80780a85aa:
      title: Commentary on the Madhyamakāvatāra—Part 1—Collection of Reasoning
      parent: Madhyamakāvatāra
    914d73ff41f144b8b5526935768a5fb4:
      title: Commentary on the Madhyamakāvatāra—Part 2—Title and Translators Homage
      parent: Madhyamakāvatāra
    940e934e3e4c4703b47e0926ab6ace37:
      title: Prologue to Introduction to the Middle Way (Madhyamakāvatāra)
      parent: Madhyamakāvatāra
    5d27799100694310bef46a05e683a7be:
      title: Concise Middle Way Aspiration
      parent: Prayers
    6add78e9319543768e3fc6ea8acf3028:
      title: Middle Way Aspiration
      parent: Prayers
created_at: '2022-03-01T04:42:52.488930'
last_modified_at: '2022-03-01T04:42:52.488933'
